# Generated by Django 5.2 on 2025-04-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(
                blank=True,
                help_text="Укажите телеграмм юзер chat-id",
                max_length=50,
                null=True,
                verbose_name="Телеграмм юзер chat-id",
            ),
        ),
    ]
